<a href="https://colab.research.google.com/github/ilafmakke/traininf-data-frame/blob/main/EDA__COURSE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```
#EDA COURSE
```

# New Section

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded=files.upload()
# Get the list of uploaded filenames
uploaded_filenames = list(uploaded.keys())
# Print the list of filenames
print(uploaded_filenames)
uploaded_csv_content = uploaded[uploaded_filenames[0]]
data = pd.read_csv(uploaded_filenames[0])
print("CSV file read successfully.")

In [ ]:
#type of eah colummn
df=data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   3333 non-null   object
 1   account length          3333 non-null   int64
 2   area code               3333 non-null   int64
 3   phone number            3333 non-null   object
 4   international plan      3333 non-null   object
 5   voice mail plan         3333 non-null   object
 6   number vmail messages   3333 non-null   int64
 7   total day minutes       3333 non-null   float64
 8   total day calls         3333 non-null   int64
 9   total day charge        3333 non-null   float64
 10  total eve minutes       3333 non-null   float64
 11  total eve calls         3333 non-null   int64
 12  total eve charge        3333 non-null   float64
 13  total night minutes     3333 non-null   float64
 14  total night calls       3333 non-null   int64
 15  total night charge      3333 non-null   float64
 16  total intl minutes      3333 non-null   float64
 17  total intl calls        3333 non-null   int64
 18  total intl charge       3333 non-null   float64
 19  customer service calls  3333 non-null   int64
 20  churn                   3333 non-null   bool
dtypes: bool(1), float64(8), int64(8), object(4)
memory usage: 524.2+ KB

In [ ]:
df.head()

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [ ]:
#last 10 rows
df.tail(10)

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
3323,IN,117,415,362-5899,no,no,0,118.4,126,20.13,...,97,21.19,227.0,56,10.22,13.6,3,3.67,5,1
3324,WV,159,415,377-1164,no,no,0,169.8,114,28.87,...,105,16.80,193.7,82,8.72,11.6,4,3.13,1,0
3325,OH,78,408,368-8555,no,no,0,193.4,99,32.88,...,88,9.94,243.3,109,10.95,9.3,4,2.51,2,0
3326,OH,96,415,347-6812,no,no,0,106.6,128,18.12,...,87,24.21,178.9,92,8.05,14.9,7,4.02,1,0
3327,SC,79,415,348-3830,no,no,0,134.7,98,22.90,...,68,16.12,221.4,128,9.96,11.8,5,3.19,2,0
3328,AZ,192,415,414-4276,no,yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,0
3329,WV,68,415,370-3271,no,no,0,231.1,57,39.29,...,55,13.04,191.3,123,8.61,9.6,4,2.59,3,0
3330,RI,28,510,328-8230,no,no,0,180.8,109,30.74,...,58,24.55,191.9,91,8.64,14.1,6,3.81,2,0
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,0
3332,TN,74,415,400-4344,no,yes,25,234.4,113,39.85,...,82,22.60,241.4,77,10.86,13.7,4,3.70,0,0

In [ ]:
df.sort_values(by='total day calls',ascending=False)

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
1121,MI,91,415,390-7930,no,no,0,154.4,165,26.25,...,121,14.31,239.9,81,10.80,11.7,4,3.16,5,1
468,AZ,86,415,392-2381,no,yes,32,70.9,163,12.05,...,121,14.17,244.9,105,11.02,11.1,5,3.00,3,0
1460,MT,80,415,361-8288,no,no,0,198.1,160,33.68,...,87,13.32,182.1,76,8.19,9.3,3,2.51,3,0
2392,WY,90,510,400-8069,no,no,0,125.4,158,21.32,...,83,22.87,238.6,103,10.74,11.0,7,2.97,1,0
1057,WV,86,415,332-2258,no,yes,38,123.0,158,20.91,...,119,11.38,138.2,103,6.22,13.3,4,3.59,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692,NE,82,408,343-2741,no,no,0,185.8,36,31.59,...,134,23.50,192.1,104,8.64,5.7,7,1.54,4,0
1989,MT,124,415,420-5652,no,yes,30,144.5,35,24.57,...,101,22.30,226.5,82,10.19,12.0,7,3.24,2,0
1144,NH,155,408,353-6300,no,no,0,216.7,30,36.84,...,125,12.27,135.3,106,6.09,10.8,1,2.92,2,0
1397,VT,101,510,413-7655,no,no,0,0.0,0,0.00,...,119,16.33,168.8,95,7.60,7.2,4,1.94,1,0
1345,SD,98,415,392-2555,no,no,0,0.0,0,0.00,...,130,13.57,167.1,88,7.52,6.8,1,1.84,4,1

In [ ]:
#nb of rows and columns
df.shape

(3333, 21)

In [ ]:
df.columns

Index(['state', 'account length', 'area code', 'phone number',
       'international plan', 'voice mail plan', 'number vmail messages',
       'total day minutes', 'total day calls', 'total day charge',
       'total eve minutes', 'total eve calls', 'total eve charge',
       'total night minutes', 'total night calls', 'total night charge',
       'total intl minutes', 'total intl calls', 'total intl charge',
       'customer service calls', 'churn'],
      dtype='object')

In [ ]:
#df['state']or df[df.columns[0]] same result
df.columns[0]

'state'

In [ ]:
df.describe()

,account length,area code,number vmail messages,total day minutes,total day calls,total day charge,total eve minutes,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls
count,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000
mean,101.064806,437.182418,8.099010,179.775098,100.435644,30.562307,200.980348,100.114311,17.083540,200.872037,100.107711,9.039325,10.237294,4.479448,2.764581,1.562856
std,39.822106,42.371290,13.688365,54.467389,20.069084,9.259435,50.713844,19.922625,4.310668,50.573847,19.568609,2.275873,2.791840,2.461214,0.753773,1.315491
min,1.000000,408.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.200000,33.000000,1.040000,0.000000,0.000000,0.000000,0.000000
25%,74.000000,408.000000,0.000000,143.700000,87.000000,24.430000,166.600000,87.000000,14.160000,167.000000,87.000000,7.520000,8.500000,3.000000,2.300000,1.000000
50%,101.000000,415.000000,0.000000,179.400000,101.000000,30.500000,201.400000,100.000000,17.120000,201.200000,100.000000,9.050000,10.300000,4.000000,2.780000,1.000000
75%,127.000000,510.000000,20.000000,216.400000,114.000000,36.790000,235.300000,114.000000,20.000000,235.300000,113.000000,10.590000,12.100000,6.000000,3.270000,2.000000
max,243.000000,510.000000,51.000000,350.800000,165.000000,59.640000,363.700000,170.000000,30.910000,395.000000,175.000000,17.770000,20.000000,20.000000,5.400000,9.000000

In [ ]:
df.describe(include=['object','bool'])
#is used to generate a summary of the DataFrame df for columns that contain categorical data (objects and booleans).

       state phone number international plan voice mail plan  churn
count   3333         3333               3333            3333   3333
unique    51         3333                  2               2      2
top       WV     382-4657                 no              no  False
freq     106            1               3010            2411   2850

In [ ]:
#is used to convert the data type of the 'churn' column in a pandas DataFrame df to integers ('int').
df['churn']=df['churn'].astype('int')
df['churn']

0       0
1       0
2       0
3       0
4       0
       ..
3328    0
3329    0
3330    0
3331    0
3332    0
Name: churn, Length: 3333, dtype: int64

In [ ]:
#count the nb of zero and one
df['churn'].value_counts()

0    2850
1     483
Name: churn, dtype: int64

In [ ]:
df['churn'].value_counts(normalize=True)

0    0.855086
1    0.144914
Name: churn, dtype: float64

In [ ]:
df.sort_values(by=['total day calls','total night calls'],ascending=[False,True])

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
1121,MI,91,415,390-7930,no,no,0,154.4,165,26.25,...,121,14.31,239.9,81,10.80,11.7,4,3.16,5,1
468,AZ,86,415,392-2381,no,yes,32,70.9,163,12.05,...,121,14.17,244.9,105,11.02,11.1,5,3.00,3,0
1460,MT,80,415,361-8288,no,no,0,198.1,160,33.68,...,87,13.32,182.1,76,8.19,9.3,3,2.51,3,0
315,MA,39,408,332-2462,no,no,0,60.4,158,10.27,...,120,26.03,123.9,46,5.58,12.4,3,3.35,1,0
1057,WV,86,415,332-2258,no,yes,38,123.0,158,20.91,...,119,11.38,138.2,103,6.22,13.3,4,3.59,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692,NE,82,408,343-2741,no,no,0,185.8,36,31.59,...,134,23.50,192.1,104,8.64,5.7,7,1.54,4,0
1989,MT,124,415,420-5652,no,yes,30,144.5,35,24.57,...,101,22.30,226.5,82,10.19,12.0,7,3.24,2,0
1144,NH,155,408,353-6300,no,no,0,216.7,30,36.84,...,125,12.27,135.3,106,6.09,10.8,1,2.92,2,0
1345,SD,98,415,392-2555,no,no,0,0.0,0,0.00,...,130,13.57,167.1,88,7.52,6.8,1,1.84,4,1
1397,VT,101,510,413-7655,no,no,0,0.0,0,0.00,...,119,16.33,168.8,95,7.60,7.2,4,1.94,1,0

In [ ]:
df['total day minutes'].mean()

179.77509750975094

In [ ]:
df[df['churn'] == 1]['total day minutes'].mean()

206.91407867494823

In [ ]:
df[df['churn'] == 1].mean()

<ipython-input-33-d5c8426bb6af>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df[df['churn'] == 1].mean()

account length            102.664596
area code                 437.817805
number vmail messages       5.115942
total day minutes         206.914079
total day calls           101.335404
total day charge           35.175921
total eve minutes         212.410145
total eve calls           100.561077
total eve charge           18.054969
total night minutes       205.231677
total night calls         100.399586
total night charge          9.235528
total intl minutes         10.700000
total intl calls            4.163561
total intl charge           2.889545
customer service calls      2.229814
churn                       1.000000
dtype: float64

In [ ]:
df.loc[:5,['international plan','state']]

  international plan state
0                 no    KS
1                 no    OH
2                 no    NJ
3                yes    OH
4                yes    OK
5                yes    AL

In [ ]:
df.iloc[-1:]

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
3332,TN,74,415,400-4344,no,yes,25,234.4,113,39.85,...,82,22.6,241.4,77,10.86,13.7,4,3.7,0,0

In [ ]:
df[-1:]

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
3332,TN,74,415,400-4344,no,yes,25,234.4,113,39.85,...,82,22.6,241.4,77,10.86,13.7,4,3.7,0,0

In [ ]:
apply and map sect

# New Section

In [ ]:
d={'yes':True, 'no':False}
df['international plan']=df['international plan'].map(d)
df['international plan']

0       False
1       False
2       False
3        True
4        True
        ...
3328    False
3329    False
3330    False
3331     True
3332    False
Name: international plan, Length: 3333, dtype: bool

In [ ]:
import  numpy as np
df.groupby(['churn'])['total day minutes','total eve minutes'].agg([np.mean,np.std,np.min])

<ipython-input-10-f99ac8e24375>:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(['churn'])['total day minutes','total eve minutes'].agg([np.mean,np.std,np.min])

      total day minutes                 total eve minutes
                   mean        std amin              mean        std  amin
churn
False        175.175754  50.181655  0.0        199.043298  50.292175   0.0
True         206.914079  68.997792  0.0        212.410145  51.728910  70.9

In [ ]:
df=df.replace({'voice mail plan':d})

# New Section

In [ ]:
pd.crosstab(df['churn'],df['international plan'])

international plan  False  True
churn
False                2664    186
True                  346    137

In [ ]:
pd.crosstab(df['churn'],df['international plan'], normalize=True)

international plan    False     True
churn
False               0.79928  0.055806
True                0.10381  0.041104

In [ ]:
df.pivot_table(['total day calls','total eve calls','total night calls'],['area code'],aggfunc='mean')

           total day calls  total eve calls  total night calls
area code
408             100.496420        99.788783          99.039379
415             100.576435       100.503927         100.398187
510             100.097619        99.671429         100.601190